### ISSUE TITLE
Unable to run TestSuite

### ISSUE THREAD

**Issue by FinalGuy** [JetBrains/workshop-jb#18]
Hi,

inspired by the talk of Svetlana on the JavaLand i just started to learn a bit kotlin. Sadly the koans won't compile on my machine. I'm using IntelliJ12 Ultimate (on OpenJDK 7) so i'm not sure if my plugin may be outdated. On the other hand i don't know how to integrate the local installation of the "kotlinc-jvm" bundle into IntelliJ - assuming that my problem is related to an old version of the kotlin compiler. 

Here is a screenshot of the compiler problem:

![compile_error](https://cloud.githubusercontent.com/assets/1208086/7107083/78999ccc-e158-11e4-9242-59db8b471fc2.png)

Greetings
Torben

**Comment by abreslav** [comment]
Hi,

The up-to-date versions of Kotlin are only compatible with up-to-date versions of IntelliJ IDEA, and the plugin you are using can not compile the workshop. 

You are welcome to use free [IntelliJ IDEA Community Edition](https://www.jetbrains.com/idea/download/).

**Comment by FinalGuy** [comment]
Hi,

koans are working fine when using IntelliJ IDEA 14. Thanks.
