### ISSUE TITLE
can't run tests

### ISSUE THREAD

**Issue by schwiz** [JetBrains/workshop-jb#19]
Just opening the project with the latest inteliJ community edition and hitting All Tests gives me 26 errors. Here is a screenshot of the first one. I have installed the kotlin plugin and ran my own 'hello world' project without issues.

![koanerror](https://cloud.githubusercontent.com/assets/891141/7442004/90e99e54-f0c5-11e4-9c92-9f68e348c892.jpg)

**Comment by kamoljan** [comment]
+1

**Comment by hhariri** [comment]
Thanks. Fixing it. It's the label notation. @ should be placed before, i.e. outerloop@ -> @outerloop

**Comment by bintree** [comment]
Sorry for inconvenience, I had reverted breaking changes

**Comment by schwiz** [comment]
Thanks for the update
