### ISSUE TITLE
Nullable Types

### ISSUE THREAD

**Issue by marcoRS** [JetBrains/workshop-jb#23]
In i_introduction._5_Nullable_Types , the first example given in the function [struggleAgainstNPE](https://github.com/JetBrains/workshop-jb/blob/master/src/i_introduction/_5_Nullable_Types/NullableTypes.kt#L20) actually does compile but the comment says it doesn't.

**Comment by Bluehorn** [comment]
Seems like the code in question was dropped in 8a5cc0803e81506778435e19e9a3d3142c269523 so I would say that this is fixed!?
