### ISSUE TITLE
Kotline Tool Window

### ISSUE THREAD

**Issue by drguildo** [JetBrains/workshop-jb#26]
The comments in `_18_Properties_.kt` say:

    You can open "View -> Tool windows -> Kotlin" and see the bytecode.

but I can't find that menu entry. Maybe it was removed in an update? I'm using IDEA 14.1.4.

**Comment by RomanBelkov** [comment]
Also did not found such an entry. Using a community IDEA 14.1.4.

Maybe it should say "Tools -> Kotlin -> Show Kotlin bytecode"?

**Comment by drguildo** [comment]
There is no `_18_Properties_.kt` file anymore and `_32_Properties_.kt` doesn't mention the bytecode viewer so maybe this should be closed?

**Comment by svtk** [comment]
Yes, thank you!
