### ISSUE TITLE
Error _15_OperatorsOverloading.kt

### ISSUE THREAD

**Issue by jchannon** [JetBrains/workshop-jb#28]
I'm a complete noob to Kotlin so I may be missing the point but the project doesn't build and currently errors in workshop-jb/src/ii_conventions/_15_OperatorsOverloading.kt

**Comment by jchannon** [comment]
<img width="459" alt="screen shot 2015-10-11 at 19 45 45" src="https://cloud.githubusercontent.com/assets/105126/10418053/b1557298-7050-11e5-839c-56e92a38d333.png">
<img width="222" alt="screen shot 2015-10-11 at 19 45 23" src="https://cloud.githubusercontent.com/assets/105126/10418054/b174d2b4-7050-11e5-9ec1-245b03de42d6.png">

**Comment by hhariri** [comment]
Change: 

fun infixNotation() {
    infix fun Int.foo(s: String) = "$s$this"

    1 foo "abc"
    // the same as:
    1.foo("abc")
}

to 

fun infixNotation() {
    fun Int.foo(s: String) = "$s$this"

    1 foo "abc"
    // the same as:
    1.foo("abc")
}

i.e. remove infix. It should build.

**Comment by jchannon** [comment]
I tried that but then it complains that TODO is an unresolved reference :smile:

**Comment by hhariri** [comment]
Hmm. I'm not seeing that. Try my fork. I just pushed it. https://github.com/hhariri/workshop-jb

**Comment by jchannon** [comment]
Yup pulled yours and this time built the whole project from root and all is fine :)

**Comment by Onizuka89** [comment]
They were a bit too eager with the infix keyword I think. It's supposed to be added later as I understood it. I'm guessing it will be in M15.

It's kind of weird that you needed to pull hhariri's fork for it to work for you, even though the fix he suggested should have been enough :/

**Comment by shuoli84** [comment]
Just remove the "infix" is enough.

**Comment by jchannon** [comment]
It is, not sure why it didnt work when i said compile the kt file and then worked when it compiled the whole project

**Comment by Ghedeon** [comment]
This, as well as many other compile errors:
```
workshop-jb/src/i_introduction/_5_Nullable_Types/NullableTypes.kt
Error:(23, 15) Kotlin: Function invocation 'size()' expected 
workshop-jb/src/i_introduction/_8_Extension_Functions/ExtensionFunctions.kt
Error:(6, 35) Kotlin: Function invocation 'length()' expected
workshop-jb/src/iii_properties/_21_HowDelegatesWork.kt
Error:(29, 1) Kotlin: Class 'EffectiveDate' must be declared abstract or implement abstract member public abstract fun get(thisRef: R, property: kotlin.PropertyMetadata): ii_conventions.MyDate defined in kotlin.properties.ReadWriteProperty

etc...
```

**Comment by RomanBelkov** [comment]
My best guess that it's because of latest commit to workshop.

As written in there, workshop is migrating to Kotlin 1.0 beta(?). Try building workshop at 9d61fb3cae35f2ff66f5ba6f3ec69864bf4171a2 commit

**Comment by Ghedeon** [comment]
Looks like the whole notion of master branch is lost here. I mean, it's master, it MUST compile! Two days ago it was almost alright, only one compilation error. And now it's ~200 errors again (I'm looking at you @svtk )). I just hope that these guys are more organized internally, otherwise we're all fucked). Yes, it's experimental, we probably shouldn't expect a lot of consistency, but I believe that working master, usage of tags, feature branches for experiments and README updates with compilation hints will help a lot... Btw, does anybody know some working Scala koans?)

**Comment by RomanBelkov** [comment]
Wow, @Ghedeon , quite a speech you gave. But have you tried updating your plugin?

You can update your plugin for, like, two days already, so this should solve the issue with compilation.

It is very hard to focus on everything, and everybody makes mistakes. All in all, JB gave us a pretty workshop to start with and the community is here to point out and try to fix the mistakes.

**Comment by Ghedeon** [comment]
You're right, sorry for jumping my seat too fast. The thing is that I'm a big fan of JB products and Kotlin in particular and it hits me every time when I'm trying to convince my team members or other people to give it a try and they have a good argument to criticize instead. Especially when I know they're right. So, let's disarm them all!)

Back to our sheep. Yes, I updated plugin two days ago and it was quite good (one compilation error), up to 976a96c78a482598962b0f79a01d1e3049717b28. Now it's a mess again. My wild guess is that it probably compiles against another plugin build, just not yet available via plugin repo.

**Comment by yole** [comment]
@Ghedeon which version of Kotlin are you using, and are you sure you don't have any local changes?? I just verified that the latest commit in master (4ce23e26f646cbd4f918855dc16b76dcceb08e58) compiles without any errors with Kotlin 1.0 Beta Candidate (1.0.0-Beta-1038).

**Comment by Ghedeon** [comment]
Not changes, but more like IDE cache. Didn't restart IDE for a while, it compiles now after performing ```Invalidate Caches/Restart..```. My apologies.

**Comment by RomanBelkov** [comment]
I guess this issue should be marked as fixed because here more than one issue is resolved here already
